apiVersion: 1

datasources:
  - name: IOTMetrics
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      # This database should be mapped to a bucket
      dbName: ${DOCKER_INFLUXDB_INIT_BUCKET}
      httpMode: GET
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}'
